name: hacker_news_scraper
description: A web scraper for scraping content from the Hackernews website.
version: 0.2.0
# homepage: https://www.example.com
# author: graphicbeacon <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  html: ^0.13.3+3
  http: ^0.12.0

dev_dependencies:
  test: ^1.0.0
